cache:
  paths:
    - maven.repository/
 
variables:
  MAVEN_OPTS: "-Dmaven.repo.local=maven.repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Xmx4g"
  JAVA_HOME: "/usr/lib/jvm/java-8-openjdk-amd64"
 
.base-job: &base-job
  before_script:
    - apt-get update -qq --force-yes > /dev/null
    - apt-get install -qq --force-yes maven openjdk-8-jdk libvulkan1 libvulkan-dev vulkan-utils > /dev/null
    - vulkaninfo
  script:
    - mvn -B package
    - mvn -B test -Dtest=ExampleRunner -Dscenery.Renderer=VulkanRenderer

scenery-nvidia:
  image: nvidia/vulkan:1.1.121-cuda-10.1-alpha
  <<: *base-job
  after_script:
    - nvidia-smi
  tags:
    - cuda
    - intel

scenery-amd:
  image: rocm/rocm-terminal
  <<: *base-job
  variables:
    SUDO: "sudo"
    GPURUN: "sudo su -m - rocm-user -c"
  before_script:
    # The rocm docker container requires the user to be in the video group which
    # can usually be set via docker's --group-add option. GitLab-Runner currently
    # has no known option for doing that. Therefore, it manually has to happen in
    # the job description. 
    - $SUDO usermod -a -G video rocm-user
    - $SUDO apt-get -qq --force-yes update > /dev/null
    - $SUDO apt-get install -qq --force-yes maven openjdk-8-jdk libvulkan1 libvulkan-dev vulkan-utils > /dev/null
    - vulkaninfo
  after_script:
    - rocm-smi
  tags:
    - amd
    - rocm


