language: java

matrix:
  include:
    - os: linux
      jdk: oraclejdk8
      sudo: false
    - os: osx
      osx_image: xcode7.3

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update        ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install gradle; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then /usr/libexec/java_home -V; fi

install:
  - cd ..
  - git clone -b scenegraph git://github.com/ClearVolume/ClearGL.git ClearGL
  - echo "include 'ClearGL'" >> settings.gradle
  - echo "include 'scenery'" >> settings.gradle
  - cd scenery

script: 
  - gradle build -Plocal=true -x test
  - gradle unitTest -Plocal=true

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
