language: java
script: "gradle build"
jdk:
  - oraclejdk8
before_script:
  - cd ..
  - git clone -b scenegraph git://github.com/ClearVolume/ClearGL.git
  - git clone git://github.com/scijava/ui-behaviour.git
  - cd ui-behaviour
  - mvn install

install: gradle assemble --stacktrace

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
